import OriginPopup from "../components/OriginPopup"
import PossibleOrigins from "../components/PossibleOrigins"
import { useState } from "react";
import './Origin.css'
import { useNavigate } from "react-router-dom";


function Origin({handleShowTab, updateCharacterInfo}) {

    var [buttonPopup, setButtonPopup] = useState(false);
    var [popupHeader, setpopupHeader] = useState();
    var [popupText, setPopupText] = useState ();
    var [popupSkill, setPopupSkill] = useState();
    var [popupPower, setPopupPower] = useState();
    var [popupPower2, setPopupPower2] = useState();
    var [activeOrigin, setActiveOrigin] = useState(null)


    function PopupChoose(head, text, skill, power, power2) {
        buttonPopup = setButtonPopup(true)
        popupHeader = setpopupHeader(head)
        popupText = setPopupText(text)
        popupSkill = setPopupSkill(skill)
        popupPower = setPopupPower(power)
        popupPower2 = setPopupPower2(power2)
        activeOrigin = setActiveOrigin(head)
    }

    const navigate = useNavigate()

    function onClick() {
        handleShowTab('class');
        navigate('/class');
        window.scrollTo(0, 0);
        updateCharacterInfo({characterOrigin: activeOrigin})
    }

    return (
        <div style={outBox}>
            <div style={{display:'flex', width:'100%', justifyContent:'center'}}>
                <img src={require("../Images/texto3.png")} alt="Header 1"></img>
            </div>
            <div className="scrollFlex" style={midBox}>
                <div style={{display:'flex', gap:'10px'}}>
                    <div style={{display:'flex', flexDirection:'column', gap:'10px'}}>
                        <PossibleOrigins mainStyle={(activeOrigin === "Acadêmico") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Acadêmico", "Você era um pesquisador ou professor universitário. De forma proposital ou não, seus estudos tocaram em assuntos misteriosos e chamaram a atenção da Ordo Realitas.", "Ciências e Investigação.", "Saber é Poder.", "Quando faz um teste usando Intelecto, você pode gastar 2 PE para receber +5 nesse teste.")} originWord={"Acadêmico"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Agente de saúde") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Agente de saúde", "Você era um profissional da saúde, como um enfermeiro, farmacêutico, médico, psicólogo ou socorrista, treinado no atendimento e cuidado de pessoas. Você pode ter sido surpreendido por um evento paranormal durante o trabalho ou mesmo cuidado de um agente da Ordem em uma emergência, que ficou surpreso com o quão bem você lidou com a situação.", "Intuição e Medicina.", "Técnica Medicinal.", "Sempre que cura um personagem, você adiciona seu Intelecto no total de PV curados.")} originWord={"Agente de saúde"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Amnésico") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Amnésico", "Você perdeu a maior parte da memória. Sabe apenas o próprio nome, ou nem isso. Sua amnésia pode ser resultado de um trauma paranormal ou mesmo de um ritual. Talvez você tenha sido vítima de cultistas? Talvez você tenha sido um cultista? Seja como for, hoje a Ordem é a única família que conhece. Quem sabe, cumprindo missões, você descubra algo sobre seu passado.", "Duas à escolha do mestre.", "Vislumbres do Passado.", "Uma vez por sessão, você pode fazerum teste de Intelecto (DT 10) para reconhecer pessoas ou lugares familiares, que tenha encontrado antes de perder a memória. Se passar, recebe 1d4 PE temporários e, a critério do mestre, uma informação útil.")} originWord={"Amnésico"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Artista") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Artista", "Você era um ator, músico, escritor, dançarino, influenciador… Seu trabalho pode ter sido inspirado por uma experiência paranormal do passado e o que o público acha que é pura criatividade, a Ordem sabe que tem um lado mais sombrio.", "Artes e Enganação.", "Magnum Opus.", "Você é famoso por uma de suas obras. Uma vez por missão, pode determinar que um personagem envolvido em uma cena de interação o reconheça. Você recebe +5 em testes de Presença e de perícias baseadas em Presença contra aquele personagem. A critério do mestre, pode receber esse bônus em outras situações nas quais seria reconhecido.")} originWord={"Artista"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Atleta") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Atleta", "Você competia em um esporte individual ou coletivo, como natação ou futebol. Seu desempenho pode ser fruto de uma influência paranormal que nem mesmo você conhecia ou você pode ter se envolvido em algum evento relacionado ao Outro Lado em uma de suas competições.", "Acrobacia e Atletismo.", "110%", "Quando faz um teste de perícia usando Força ou Agilidade (exceto Luta e Pontaria) você pode gastar 2 PE para receber +5 nesse teste.")} originWord={"Atleta"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Chef") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Chef", "Você é um cozinheiro amador ou profissional. Talvez trabalhasse em um restaurante, talvez simplesmente gostasse de cozinhar para a família e amigos. Como sua comida fez com que você se envolvesse com o paranormal? Ninguém sabe. Mas os outros agentes adoram quando você vai para a missão!", "Fortitude e Profissão (cozinheiro).", "Ingrediente Secreto.", "Em cenas de interlúdio, você pode fazer a ação alimentar-se para cozinhar um prato especial. Você, e todos os membros do grupo que fizeram a ação alimentar-se, recebem o benefício de dois pratos (caso o mesmo benefício seja escolhido duas vezes, seus efeitos se acumulam).")} originWord={"Chef"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Criminoso") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Criminoso", "Você vivia uma vida fora da lei, seja como mero batedor de carteiras, seja como membro de uma facção criminosa. Em algum momento, você se envolveu em um assunto da Ordem — talvez tenha roubado um item amaldiçoado? A organização, por sua vez, achou melhor recrutar seus talentos do que ter você como um estorvo.", "Crime e Furtividade.", "O Crime Compensa.", "No final de uma missão, escolha um item encontrado na missão. Em sua próxima missão, você pode incluir esse item em seu inventário sem que ele conte em seu limite de itens por patente.")} originWord={"Criminoso"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Cultista Arrependido") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Cultista Arrependido", "Você fez parte de um culto paranormal. Talvez fossem ignorantes iludidos, que acreditavam estar contatando entidades benevolentes. Talvez soubessem exatamente o que estavam fazendo. Seja como for, algo abriu seus olhos e agora você luta pelo lado certo — embora carregue para sempre traços de sua vida pregressa. Outros membros da Ordem podem desconfiar de sua conversão e você sabe que precisará se esforçar para conquistar a confiança de todos.", "Ocultismo e Religião.", "Traços do Outro Lado.", "Você possui um poder paranormal à sua escolha. Porém, começa o jogo com metade da Sanidade normal para sua classe.")} originWord={"Cultista Arrependido"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Desgarrado") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Desgarrado", "Você não vivia de acordo com as normas da sociedade. Podia ser um eremita, uma pessoa em situação de rua ou simplesmente alguém que descobriu o paranormal e abandonou sua rotina — sabendo o quão frágil era a existência humana, não conseguia simplesmente continuar indo para o trabalho todo dia. De qualquer forma, a vida sem os confortos modernos o deixou mais forte.", "Fortitude e Sobrevivência.", "Calejado", "Você recebe +1 PV para cada 5% de NEX.")} originWord={"Desgarrado"}/>
                    </div>
                    <div style={{display:'flex', flexDirection:'column', gap:'10px'}}>
                        <PossibleOrigins mainStyle={(activeOrigin === "Engenheiro") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Engenheiro", "Enquanto os acadêmicos estão preocupados com teorias, você coloca a mão na massa, seja como engenheiro profissional, seja como inventor de garagem. Provavelmente você criou algum dispositivo paranormal que chamou a atenção da Ordem.", "Profissão e Tecnologia.", "Ferramenta Favorita.", "Um item a sua escolha (exceto armas) conta como uma categoria abaixo (por exemplo, um item de categoria II conta como categoria I para você).")} originWord={"Engenheiro"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Executivo") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Executivo", "Você possuía um trabalho de escritório em uma grande empresa, banco ou corporação. Era um administrador, advogado, contador ou de qualquer outra profissão que lida com papelada e burocracia. Sua vida era bastante normal, até que você descobriu algo que não devia. Talvez o sucesso da empresa residisse em um ritual? Talvez toda a corporação fosse fachada para um culto e o presidente, um líder cultista envolvido com entidades paranormais? Após essa descoberta, você foi recrutado pela Ordem e trocou seu trabalho de escritório por missões de campo — hoje, sua vida é tudo, menos normal.", "Diplomacia e Profissão.", "Processo Otimizado.", "Sempre que faz um teste de perícia durante um teste estendido, ou uma ação para revisar documentos (físicos ou digitais), pode pagar 2 PE para receber +5 nesse teste.")} originWord={"Executivo"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Investigador") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Investigador", "Você era um investigador do governo, como um perito forense ou policial federal, ou privado, como um detetive particular. Pode ter tido contato com o paranormal em algum caso ou ter sido recrutado pela Ordem por suas habilidades de resolução de mistérios.", "Investigação e Percepção.", "Faro para Pistas.", "Uma vez por cena, quando fizer um teste para procurar pistas, você pode gastar 1 PE para receber +5 nesse teste.")} originWord={"Investigador"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Lutador") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Lutador", "Você pratica uma arte marcial ou esporte de luta, ou cresceu em um bairro perigoso onde aprendeu briga de rua. Já quebrou muitos ossos, tanto seus quanto dos outros. Pode ter conhecido a Ordem após um torneio secreto envolvendo entidades do Outro Lado ou ter sido recrutado pela sua capacidade de luta.", "Luta e Reflexos.", "Mão Pesada.", "Você recebe +2 em rolagens de dano com ataques corpo a corpo.")} originWord={"Lutador"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Magnata") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Magnata", "Você possui muito dinheiro ou patrimônio. Pode ser o herdeiro de uma família antiga ligada ao oculto, ter criado e vendido uma empresa e decidido usar sua riqueza para uma causa maior, ou ter ganho uma loteria após inadvertidamente escolher números amaldiçoados que formavam um ritual.", "Diplomacia e Pilotagem.", "Patrocinador da Ordem.", "Seu limite de crédito é sempre considerado um acima do atual.")} originWord={"Magnata"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Mercenário") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Mercenário", "Você é um soldado de aluguel, que trabalha sozinho ou como parte de alguma organização que vendeserviços militares. Escoltas e assassinatos fizeram parte de sua rotina por tempo o suficiente para você se envolver em alguma situação com o paranormal.", "Iniciativa e Intimidação.", "Posição de Combate.", "No primeiro turno de cadacena de ação, você pode gastar 2 PE para receber uma ação de movimento adicional.")} originWord={"Mercenário"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Militar") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Militar", "Você serviu em uma força militar, como o exército ou a marinha. Passou muito tempo treinando com armas de fogo, até se tornar um perito no uso delas. Acostumado a obedecer ordens e partir em missões, está em casa na Ordo Realitas. O inimigo é diferente, mas um tiro bem dado continua resolvendo o problema.", "Pontaria e Tática.", "Para Bellum", "Você recebe +2 em rolagens de dano com armas de fogo.")} originWord={"Militar"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Operário") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Operário", "Pedreiro, industriário, operador de máquinas em uma fábrica… Você passou uma parte de sua vida em um emprego braçal, desempenhando atividades práticas que lhe deram uma visão pragmática do mundo. Sua rotina mundana, entretanto, foi confrontada de alguma forma pelo paranormal, e você não consegue mais esquecer tudo que viu sobre os mistérios do mundo.", "Fortitude e Profissão.", "Ferramenta de Trabalho.", "Escolha uma arma simples ou tática que, a critério do mestre, poderia ser usada como ferramenta em sua profissão (como uma marreta para um pedreiro). Você sabe usar a arma escolhida e recebe +1 em testes de ataque, rolagens de dano e margem de ameaça com ela.")} originWord={"Operário"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Policial") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Policial", "Você fez parte de uma força de segurança pública, civil ou militar. Em alguma patrulha ou chamado se deparou com um caso paranormal e sobreviveu para contar a história.", "Percepção e Pontaria.", "Patrulha", "Você recebe +2 em Defesa.")} originWord={"Policial"}/>
                    </div>
                    <div style={{display:'flex', flexDirection:'column', gap:'10px'}}>
                        <PossibleOrigins mainStyle={(activeOrigin === "Religioso") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Religioso", "Você é devoto ou sacerdote de uma fé. Independentemente da religião que pratica, se dedica a auxiliar as pessoas com problemas espirituais. A partir disso, teve contato com o paranormal, o que fez com que fosse convocado pela Ordem.", "Religião e Vontade.", "Acalentar", "Você recebe +5 em testes de Religião para acalmar. Além disso, quando acalma uma pessoa, ela recebe um número de pontos de Sanidade igual a 1d6 + a sua Presença.")} originWord={"Religioso"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Servidor Público") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Servidor Público", "Você possuía carreira em um órgão do governo, lidando com burocracia e atendendo pessoas. Sua rotina foi quebrada quando você viu que o prefeito era um cultista ou que a câmara de vereadores se reunia à noite para realizar rituais. Quando os próprios representantes do povo estão dispostos a sacrificá-lo para entidades malignas, onde reside nossa esperança? Hoje, você sabe a resposta para essa pergunta: na Ordo Realitas.", "Intuição e Vontade.", "Espírito cívico", "Sempre que faz um teste para ajudar, você pode gastar 1 PE para aumentar o bônus concedido em +2.")} originWord={"Servidor Público"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Teórico da Conspiração") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Teórico da Conspiração", "A humanidade nunca pisou na lua. Reptilianos ocupam importantes cargos públicos. A Terra é plana… E secretamente governada pelos Illuminati. Você sabe isso tudo, pois investigou a fundo esses importantes assuntos. Quando sua pesquisa esbarrou no paranormal, você foi recrutado. Na Ordem, sua loucura/determinação será usada para um bom propósito.", "Investigação e Ocultismo.", "Eu já sabia", "Você não se abala tanto com entidades ou anomalias. Afinal, sempre soube que isso tudo existia. Você recebe resistência a dano mental igual ao seu Intelecto.")} originWord={"Teórico da Conspiração"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "T.I.") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("T.I.", "Programador, engenheiro de software ou simplesmente “o cara da T.I.”, você tem treinamento e experiência para lidar com sistemas informatizados. Seu talento (ou curiosidade exagerada) chamou a atenção da Ordem.", "Investigação e Tecnologia.", "Motor de busca", "A critério do mestre, sempre que tiver acesso a internet, você pode gastar 2 PE para substituir um teste de perícia qualquer por um teste de Tecnologia.")} originWord={"T.I."}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Trabalhador Rural") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Trabalhador Rural", "Você trabalhava no campo ou em áreas isoladas, como fazendeiro, pescador, biólogo, veterinário… Você se acostumou com o convívio com a natureza e os animais e talvez tenha ouvido uma ou outra história de fantasmas ao redor da fogueira. Em algum momento da sua vida, porém, descobriu que muitas dessas histórias são verdadeiras.", "Adestramento e Sobrevivência.", "Desbravador", "Quando faz um teste de Adestramento ou Sobrevivência, você pode gastar 2 PE para receber +5 nesse teste. Além disso, você não sofre penalidade em deslocamento por terreno dif ícil.")} originWord={"Trabalhador Rural"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Trambiqueiro") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Trambiqueiro", "Uma vida digna exige muito trabalho, então é melhor nem tentar. Você vivia de pequenos golpes, jogatina ilegal e falcatruas. Certo dia, enganou a pessoa errada; no dia seguinte, se viu servindo à Ordem. Pelo menos agora tem a chance de usar sua lábia para o bem.", "Crime e Enganação.", "Impostor", "Uma vez por cena, você pode gastar 2 PE para substituir um teste de perícia qualquer por um teste de Enganação.")} originWord={"Trambiqueiro"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Universitário") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Universitário", "Você era aluno de uma faculdade. Em sua rotina de estudos, provas e festas, acabou descobrindo algo — talvez um livro amaldiçoado na antiga biblioteca do campus? Por seu achado, foi convocado pela Ordem. Agora, estuda com mais afinco: nesse novo curso, ouviu dizer que as provas podem ser mortais.", "Atualidades e Investigação.", "Dedicação", "Você recebe +1 PE, e mais 1 PE adicional a cada NEX ímpar (15%, 25%…). Além disso, seu limite de PE por turno aumenta em 1 (em NEX 5% seu limite é 2, em NEX 10% é 3 e assim por diante; isso não afeta a DT de seus efeitos).")} originWord={"Universitário"}/>
                        <PossibleOrigins mainStyle={(activeOrigin === "Vítima") ? activeButtonStyle : inactiveButtonStyle} onClick={() => PopupChoose("Vítima", "Em algum momento de sua vida — infância, juventude ou início da vida adulta — você encontrou o paranormal… E a experiência não foi nada boa. Você viu os espíritos dos mortos, foi atacado por uma entidade ou mesmo foi sequestrado para ser sacrificado em um ritual impedido no último momento. A experiência foi traumática, mas você não se abateu; em vez disso, decidiu lutar para impedir que outros inocentes passem pelo mesmo. E, já tendo sido vítima do paranormal, se tornou habilidoso em evitar perigos.", "Reflexos e Vontade.", "Cicatrizes psicológicas", "Você recebe +1 de Sanidade para cada 5% de NEX.")} originWord={"Vítima"}/>
                    </div>
                </div>
                <div >
                    <OriginPopup trigger={buttonPopup} setTrigger={setButtonPopup} originHead={popupHeader} originText={popupText} originSkill={popupSkill} originPower1={popupPower} originPower2={popupPower2}></OriginPopup>
                </div>
            </div>
            <div>
                <button 
                    onClick={onClick} 
                    disabled={(activeOrigin === null) ? true : false}
                    style={(activeOrigin === null) ? disabledNextButton : enabledNextButton}
                >
                    Próximo passo
                </button>
            </div>
        </div>
    )
}

const outBox = {gap:'30px', display:'flex', padding:'40px 200px', flexDirection:'column', alignItems:'center'}
const midBox = {display:"flex", width:'100%', gap:'12px'}
const activeButtonStyle = {fontFamily:'"nitti-typewriter-normal", sans-serif', fontWeight:'400', fontStyle:'normal', cursor:"pointer", display:"flex", backgroundColor:"#B22729", border:"1px solid white", width:"200px", height:"70px", borderRadius:"5px", alignItems:"center", padding:"0px 20px", color:"white", flexDirection:"row", justifyContent:"space-between"}
const inactiveButtonStyle = {fontFamily:'"nitti-typewriter-normal", sans-serif', fontWeight:'400', fontStyle:'normal', cursor:"pointer", display:"flex", backgroundColor:"#020202", border:"1px solid white", width:"200px", height:"70px", borderRadius:"5px", alignItems:"center", padding:"0px 20px", color:"white", flexDirection:"row", justifyContent:"space-between"}
const disabledNextButton = {backgroundColor:"#020202", lineHeight:"20px", borderRadius:"5px", fontSize:"16px", border:"1px solid white", width:"200px", height:"70px", color:'white', opacity:'20%'}
const enabledNextButton = {cursor:'pointer', backgroundColor:"#020202", lineHeight:"20px", borderRadius:"5px", fontSize:"16px", border:"1px solid white", width:"200px", height:"70px", color:'white'}
export default Origin