import "./PerksTable.css"

function PerksTable() {

  return (
    <div>
        <table className="perks" style={{borderSpacing:"0px", color:"white", textAlign:"center", width:'430px', backgroundColor:'#0f1216', fontSize:'15px'}}>
            <tr>
                <th style={{width:'110px'}}>Perícia</th>
                <th style={{width:'110px'}}>Atributo Base</th>
                <th style={{width:'115px'}}>Somente treinada?</th>
                <th style={{width:'50px'}}>Carga</th>
                <th style={{width:'50px'}}>Kit</th>
            </tr>
            <tr>
                <td>Acrobacia</td>
                <td>Agilidade</td>
                <td>-</td>
                <td>Sim</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Adestramento</td>
                <td>Presença</td>
                <td>Sim</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Artes</td>
                <td>Presença</td>
                <td>Sim</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Atletismo</td>
                <td>Força</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Atualidades</td>
                <td>Intelecto</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Ciências</td>
                <td>Intelecto</td>
                <td>Sim</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Crime</td>
                <td>Agilidade</td>
                <td>Sim</td>
                <td>Sim</td>
                <td>Sim</td>
            </tr>
            <tr>
                <td>Diplomacia</td>
                <td>Presença</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Enganação</td>
                <td>Presença</td>
                <td>-</td>
                <td>-</td>
                <td>Sim</td>
            </tr>
            <tr>
                <td>Fortitude</td>
                <td>Vigor</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Furtividade</td>
                <td>Agilidade</td>
                <td>-</td>
                <td>Sim</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Iniciativa</td>
                <td>Agilidade</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Intimidação</td>
                <td>Presença</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Intuição</td>
                <td>Presença</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Investigação</td>
                <td>Intelecto</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Luta</td>
                <td>Força</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Medicina</td>
                <td>Intelecto</td>
                <td>-</td>
                <td>-</td>
                <td>Sim</td>
            </tr>
            <tr>
                <td>Ocultismo</td>
                <td>Intelecto</td>
                <td>Sim</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Percepção</td>
                <td>Presença</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Pilotagem</td>
                <td>Agilidade</td>
                <td>Sim</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Pontaria</td>
                <td>Agilidade</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Profissão</td>
                <td>Intelecto</td>
                <td>Sim</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Reflexos</td>
                <td>Agilidade</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Religião</td>
                <td>Presença</td>
                <td>Sim</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Sobrevivência</td>
                <td>Intelecto</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Tática</td>
                <td>Intelecto</td>
                <td>Sim</td>
                <td>-</td>
                <td>-</td>
            </tr>
            <tr>
                <td>Tecnologia</td>
                <td>Intelecto</td>
                <td>Sim</td>
                <td>-</td>
                <td>Sim</td>
            </tr>
            <tr>
                <td>Vontade</td>
                <td>Presença</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            </tr>
        </table>
    </div>
  );
}

export default PerksTable;


